name: 'BuildDLL'
on:
  push:
    branches:
      - 'main'
jobs:
  BuildDLL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "nextzlog/zylo"
          version: "tags/zbuild"
          file: "zbuild-linux"
          token: ${{secrets.GITHUB_TOKEN}}
      - run: sudo chmod a+x zbuild-linux
      - run: ./zbuild-linux setup
      - run: ./zbuild-linux compile
      - uses: svenstaro/upload-release-action@v2
        with:
          tag: nightly
          file: soumuAPI.dll
          overwrite: true
          file_glob: true
          repo_token: ${{secrets.GITHUB_TOKEN}}
